/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 设备信息分组表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseEquipmentGroup implements Serializable {

    private static final long serialVersionUID = -1146290751;

    private final Long    id;
    private final Long    roleId;
    private final Long    equipmentId;
    private final Integer invalid;

    public ElfBaseEquipmentGroup(ElfBaseEquipmentGroup value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.equipmentId = value.equipmentId;
        this.invalid = value.invalid;
    }

    public ElfBaseEquipmentGroup(
        Long    id,
        Long    roleId,
        Long    equipmentId,
        Integer invalid
    ) {
        this.id = id;
        this.roleId = roleId;
        this.equipmentId = equipmentId;
        this.invalid = invalid;
    }

    public Long getId() {
        return this.id;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public Long getEquipmentId() {
        return this.equipmentId;
    }

    public Integer getInvalid() {
        return this.invalid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfBaseEquipmentGroup (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(equipmentId);
        sb.append(", ").append(invalid);

        sb.append(")");
        return sb.toString();
    }
}
