/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 所属机构，和用户对应的详细信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseMechanismGroup implements Serializable {

    private static final long serialVersionUID = 1932806246;

    private final Long id;
    private final Long mechanismId;
    private final Long userId;

    public ElfBaseMechanismGroup(ElfBaseMechanismGroup value) {
        this.id = value.id;
        this.mechanismId = value.mechanismId;
        this.userId = value.userId;
    }

    public ElfBaseMechanismGroup(
        Long id,
        Long mechanismId,
        Long userId
    ) {
        this.id = id;
        this.mechanismId = mechanismId;
        this.userId = userId;
    }

    public Long getId() {
        return this.id;
    }

    public Long getMechanismId() {
        return this.mechanismId;
    }

    public Long getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfBaseMechanismGroup (");

        sb.append(id);
        sb.append(", ").append(mechanismId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
