/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 角色信息管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseRole implements Serializable {

    private static final long serialVersionUID = -1709606157;

    private final Long      id;
    private final String    roleName;
    private final Long      mechanismId;
    private final Timestamp createDate;

    public ElfBaseRole(ElfBaseRole value) {
        this.id = value.id;
        this.roleName = value.roleName;
        this.mechanismId = value.mechanismId;
        this.createDate = value.createDate;
    }

    public ElfBaseRole(
        Long      id,
        String    roleName,
        Long      mechanismId,
        Timestamp createDate
    ) {
        this.id = id;
        this.roleName = roleName;
        this.mechanismId = mechanismId;
        this.createDate = createDate;
    }

    public Long getId() {
        return this.id;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public Long getMechanismId() {
        return this.mechanismId;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfBaseRole (");

        sb.append(id);
        sb.append(", ").append(roleName);
        sb.append(", ").append(mechanismId);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
