/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 用来做国际化翻译后台的提示信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseLanguage implements Serializable {

    private static final long serialVersionUID = -1285527716;

    private final Long    id;
    private final Integer country;
    private final Long    key;
    private final String  msg;

    public ElfBaseLanguage(ElfBaseLanguage value) {
        this.id = value.id;
        this.country = value.country;
        this.key = value.key;
        this.msg = value.msg;
    }

    public ElfBaseLanguage(
        Long    id,
        Integer country,
        Long    key,
        String  msg
    ) {
        this.id = id;
        this.country = country;
        this.key = key;
        this.msg = msg;
    }

    public Long getId() {
        return this.id;
    }

    public Integer getCountry() {
        return this.country;
    }

    public Long getKey() {
        return this.key;
    }

    public String getMsg() {
        return this.msg;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfBaseLanguage (");

        sb.append(id);
        sb.append(", ").append(country);
        sb.append(", ").append(key);
        sb.append(", ").append(msg);

        sb.append(")");
        return sb.toString();
    }
}
