/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 设备信息维护表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseEquipment implements Serializable {

    private static final long serialVersionUID = 653441749;

    private final Long   id;
    private final String equipmentName;
    private final Long   mechanismId;

    public ElfBaseEquipment(ElfBaseEquipment value) {
        this.id = value.id;
        this.equipmentName = value.equipmentName;
        this.mechanismId = value.mechanismId;
    }

    public ElfBaseEquipment(
        Long   id,
        String equipmentName,
        Long   mechanismId
    ) {
        this.id = id;
        this.equipmentName = equipmentName;
        this.mechanismId = mechanismId;
    }

    public Long getId() {
        return this.id;
    }

    public String getEquipmentName() {
        return this.equipmentName;
    }

    public Long getMechanismId() {
        return this.mechanismId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfBaseEquipment (");

        sb.append(id);
        sb.append(", ").append(equipmentName);
        sb.append(", ").append(mechanismId);

        sb.append(")");
        return sb.toString();
    }
}
