/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 菜单权限映射表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfMenuDataMapping implements Serializable {

    private static final long serialVersionUID = 1354170822;

    private final Long    id;
    private final Long    menuId;
    private final Integer invalid;
    private final Long    roleId;

    public ElfMenuDataMapping(ElfMenuDataMapping value) {
        this.id = value.id;
        this.menuId = value.menuId;
        this.invalid = value.invalid;
        this.roleId = value.roleId;
    }

    public ElfMenuDataMapping(
        Long    id,
        Long    menuId,
        Integer invalid,
        Long    roleId
    ) {
        this.id = id;
        this.menuId = menuId;
        this.invalid = invalid;
        this.roleId = roleId;
    }

    public Long getId() {
        return this.id;
    }

    public Long getMenuId() {
        return this.menuId;
    }

    public Integer getInvalid() {
        return this.invalid;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfMenuDataMapping (");

        sb.append(id);
        sb.append(", ").append(menuId);
        sb.append(", ").append(invalid);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
