/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 基础的菜单信息维护
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfMenuData implements Serializable {

    private static final long serialVersionUID = -1146390159;

    private final Long   id;
    private final Long   fatherid;
    private final String name;
    private final String icon;
    private final String path;
    private final String component;
    private final Long   equipmentId;

    public ElfMenuData(ElfMenuData value) {
        this.id = value.id;
        this.fatherid = value.fatherid;
        this.name = value.name;
        this.icon = value.icon;
        this.path = value.path;
        this.component = value.component;
        this.equipmentId = value.equipmentId;
    }

    public ElfMenuData(
        Long   id,
        Long   fatherid,
        String name,
        String icon,
        String path,
        String component,
        Long   equipmentId
    ) {
        this.id = id;
        this.fatherid = fatherid;
        this.name = name;
        this.icon = icon;
        this.path = path;
        this.component = component;
        this.equipmentId = equipmentId;
    }

    public Long getId() {
        return this.id;
    }

    public Long getFatherid() {
        return this.fatherid;
    }

    public String getName() {
        return this.name;
    }

    public String getIcon() {
        return this.icon;
    }

    public String getPath() {
        return this.path;
    }

    public String getComponent() {
        return this.component;
    }

    public Long getEquipmentId() {
        return this.equipmentId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElfMenuData (");

        sb.append(id);
        sb.append(", ").append(fatherid);
        sb.append(", ").append(name);
        sb.append(", ").append(icon);
        sb.append(", ").append(path);
        sb.append(", ").append(component);
        sb.append(", ").append(equipmentId);

        sb.append(")");
        return sb.toString();
    }
}
