/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseSession;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 维护用户当前登入的session
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseSessionRecord extends UpdatableRecordImpl<ElfBaseSessionRecord> implements Record6<Long, String, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1939919420;

    /**
     * Setter for <code>elf.elf_base_session.id</code>.
     */
    public ElfBaseSessionRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_session.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_session.session_code</code>. 显示给前台的session_code,64位的UUID防止用户进行暴力破解
     */
    public ElfBaseSessionRecord setSessionCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_session.session_code</code>. 显示给前台的session_code,64位的UUID防止用户进行暴力破解
     */
    public String getSessionCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_session.user_id</code>. 用户ID
     */
    public ElfBaseSessionRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_session.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>elf.elf_base_session.equipment_id</code>. 设备类型
     */
    public ElfBaseSessionRecord setEquipmentId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_session.equipment_id</code>. 设备类型
     */
    public Long getEquipmentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>elf.elf_base_session.last_date</code>. 最后操作时间
     */
    public ElfBaseSessionRecord setLastDate(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_session.last_date</code>. 最后操作时间
     */
    public Timestamp getLastDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>elf.elf_base_session.create_date</code>. 创建时间
     */
    public ElfBaseSessionRecord setCreateDate(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_session.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseSession.ELF_BASE_SESSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ElfBaseSession.ELF_BASE_SESSION.SESSION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ElfBaseSession.ELF_BASE_SESSION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ElfBaseSession.ELF_BASE_SESSION.EQUIPMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ElfBaseSession.ELF_BASE_SESSION.LAST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ElfBaseSession.ELF_BASE_SESSION.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSessionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSessionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord value2(String value) {
        setSessionCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord value4(Long value) {
        setEquipmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord value5(Timestamp value) {
        setLastDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord value6(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseSessionRecord values(Long value1, String value2, Long value3, Long value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseSessionRecord
     */
    public ElfBaseSessionRecord() {
        super(ElfBaseSession.ELF_BASE_SESSION);
    }

    /**
     * Create a detached, initialised ElfBaseSessionRecord
     */
    public ElfBaseSessionRecord(Long id, String sessionCode, Long userId, Long equipmentId, Timestamp lastDate, Timestamp createDate) {
        super(ElfBaseSession.ELF_BASE_SESSION);

        set(0, id);
        set(1, sessionCode);
        set(2, userId);
        set(3, equipmentId);
        set(4, lastDate);
        set(5, createDate);
    }
}
