/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用来维护用户信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseUserRecord extends UpdatableRecordImpl<ElfBaseUserRecord> implements Record9<Long, String, String, String, Long, Long, Timestamp, Integer, String> {

    private static final long serialVersionUID = 885421103;

    /**
     * Setter for <code>elf.elf_base_user.id</code>. 唯一ID
     */
    public ElfBaseUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.id</code>. 唯一ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_user.user_name</code>. 用户名称
     */
    public ElfBaseUserRecord setUserName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.user_name</code>. 用户名称
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_user.login_name</code>. 登入名称
     */
    public ElfBaseUserRecord setLoginName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.login_name</code>. 登入名称
     */
    public String getLoginName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>elf.elf_base_user.email</code>. 用户邮箱地址
     */
    public ElfBaseUserRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.email</code>. 用户邮箱地址
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>elf.elf_base_user.language</code>. 用户所属语言
     */
    public ElfBaseUserRecord setLanguage(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.language</code>. 用户所属语言
     */
    public Long getLanguage() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>elf.elf_base_user.role_id</code>. 用户所属的角色ID
     */
    public ElfBaseUserRecord setRoleId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.role_id</code>. 用户所属的角色ID
     */
    public Long getRoleId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>elf.elf_base_user.create_date</code>. 用户创建日期
     */
    public ElfBaseUserRecord setCreateDate(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.create_date</code>. 用户创建日期
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>elf.elf_base_user.online</code>. 在线时长 单位分
     */
    public ElfBaseUserRecord setOnline(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.online</code>. 在线时长 单位分
     */
    public Integer getOnline() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>elf.elf_base_user.password</code>. 用户密码
     */
    public ElfBaseUserRecord setPassword(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_user.password</code>. 用户密码
     */
    public String getPassword() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, Long, Long, Timestamp, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, Long, Long, Timestamp, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseUser.ELF_BASE_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ElfBaseUser.ELF_BASE_USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ElfBaseUser.ELF_BASE_USER.LOGIN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ElfBaseUser.ELF_BASE_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ElfBaseUser.ELF_BASE_USER.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ElfBaseUser.ELF_BASE_USER.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ElfBaseUser.ELF_BASE_USER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ElfBaseUser.ELF_BASE_USER.ONLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ElfBaseUser.ELF_BASE_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLoginName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getOnline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLoginName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getOnline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value3(String value) {
        setLoginName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value5(Long value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value6(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value7(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value8(Integer value) {
        setOnline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord value9(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseUserRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, Timestamp value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseUserRecord
     */
    public ElfBaseUserRecord() {
        super(ElfBaseUser.ELF_BASE_USER);
    }

    /**
     * Create a detached, initialised ElfBaseUserRecord
     */
    public ElfBaseUserRecord(Long id, String userName, String loginName, String email, Long language, Long roleId, Timestamp createDate, Integer online, String password) {
        super(ElfBaseUser.ELF_BASE_USER);

        set(0, id);
        set(1, userName);
        set(2, loginName);
        set(3, email);
        set(4, language);
        set(5, roleId);
        set(6, createDate);
        set(7, online);
        set(8, password);
    }
}
