/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseLanguage;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用来做国际化翻译后台的提示信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseLanguageRecord extends UpdatableRecordImpl<ElfBaseLanguageRecord> implements Record4<Long, Integer, Long, String> {

    private static final long serialVersionUID = 989535613;

    /**
     * Setter for <code>elf.elf_base_language.id</code>.
     */
    public ElfBaseLanguageRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_language.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_language.country</code>. 所属国家，按照国际手机号码区号进行编码
     */
    public ElfBaseLanguageRecord setCountry(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_language.country</code>. 所属国家，按照国际手机号码区号进行编码
     */
    public Integer getCountry() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_language.key</code>. 所属的KEY
     */
    public ElfBaseLanguageRecord setKey(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_language.key</code>. 所属的KEY
     */
    public Long getKey() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>elf.elf_base_language.msg</code>. 详细的消息
     */
    public ElfBaseLanguageRecord setMsg(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_language.msg</code>. 详细的消息
     */
    public String getMsg() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Integer, Long, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Integer, Long, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseLanguage.ELF_BASE_LANGUAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ElfBaseLanguage.ELF_BASE_LANGUAGE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ElfBaseLanguage.ELF_BASE_LANGUAGE.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ElfBaseLanguage.ELF_BASE_LANGUAGE.MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseLanguageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseLanguageRecord value2(Integer value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseLanguageRecord value3(Long value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseLanguageRecord value4(String value) {
        setMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseLanguageRecord values(Long value1, Integer value2, Long value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseLanguageRecord
     */
    public ElfBaseLanguageRecord() {
        super(ElfBaseLanguage.ELF_BASE_LANGUAGE);
    }

    /**
     * Create a detached, initialised ElfBaseLanguageRecord
     */
    public ElfBaseLanguageRecord(Long id, Integer country, Long key, String msg) {
        super(ElfBaseLanguage.ELF_BASE_LANGUAGE);

        set(0, id);
        set(1, country);
        set(2, key);
        set(3, msg);
    }
}
