/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseEquipmentGroup;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 设备信息分组表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseEquipmentGroupRecord extends UpdatableRecordImpl<ElfBaseEquipmentGroupRecord> implements Record4<Long, Long, Long, Integer> {

    private static final long serialVersionUID = -213516667;

    /**
     * Setter for <code>elf.elf_base_equipment_group.id</code>.
     */
    public ElfBaseEquipmentGroupRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_equipment_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_equipment_group.role_id</code>. 角色ID
     */
    public ElfBaseEquipmentGroupRecord setRoleId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_equipment_group.role_id</code>. 角色ID
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_equipment_group.equipment_id</code>. 设备ID
     */
    public ElfBaseEquipmentGroupRecord setEquipmentId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_equipment_group.equipment_id</code>. 设备ID
     */
    public Long getEquipmentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>elf.elf_base_equipment_group.invalid</code>. 是否失效 0表示否 1表示失效
     */
    public ElfBaseEquipmentGroupRecord setInvalid(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_equipment_group.invalid</code>. 是否失效 0表示否 1表示失效
     */
    public Integer getInvalid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.EQUIPMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.INVALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getInvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getInvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroupRecord value2(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroupRecord value3(Long value) {
        setEquipmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroupRecord value4(Integer value) {
        setInvalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroupRecord values(Long value1, Long value2, Long value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseEquipmentGroupRecord
     */
    public ElfBaseEquipmentGroupRecord() {
        super(ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP);
    }

    /**
     * Create a detached, initialised ElfBaseEquipmentGroupRecord
     */
    public ElfBaseEquipmentGroupRecord(Long id, Long roleId, Long equipmentId, Integer invalid) {
        super(ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP);

        set(0, id);
        set(1, roleId);
        set(2, equipmentId);
        set(3, invalid);
    }
}
