/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseRole;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色信息管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseRoleRecord extends UpdatableRecordImpl<ElfBaseRoleRecord> implements Record4<Long, String, Long, Timestamp> {

    private static final long serialVersionUID = -1949141764;

    /**
     * Setter for <code>elf.elf_base_role.id</code>.
     */
    public ElfBaseRoleRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_role.role_name</code>. 角色名称
     */
    public ElfBaseRoleRecord setRoleName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_role.role_name</code>. 角色名称
     */
    public String getRoleName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_role.mechanism_id</code>. 所属仓库
     */
    public ElfBaseRoleRecord setMechanismId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_role.mechanism_id</code>. 所属仓库
     */
    public Long getMechanismId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>elf.elf_base_role.create_date</code>. 创建时间
     */
    public ElfBaseRoleRecord setCreateDate(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_role.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseRole.ELF_BASE_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ElfBaseRole.ELF_BASE_ROLE.ROLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ElfBaseRole.ELF_BASE_ROLE.MECHANISM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ElfBaseRole.ELF_BASE_ROLE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getMechanismId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMechanismId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseRoleRecord value2(String value) {
        setRoleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseRoleRecord value3(Long value) {
        setMechanismId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseRoleRecord value4(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseRoleRecord values(Long value1, String value2, Long value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseRoleRecord
     */
    public ElfBaseRoleRecord() {
        super(ElfBaseRole.ELF_BASE_ROLE);
    }

    /**
     * Create a detached, initialised ElfBaseRoleRecord
     */
    public ElfBaseRoleRecord(Long id, String roleName, Long mechanismId, Timestamp createDate) {
        super(ElfBaseRole.ELF_BASE_ROLE);

        set(0, id);
        set(1, roleName);
        set(2, mechanismId);
        set(3, createDate);
    }
}
