/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseMechanismGroup;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 所属机构，和用户对应的详细信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseMechanismGroupRecord extends UpdatableRecordImpl<ElfBaseMechanismGroupRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 829557120;

    /**
     * Setter for <code>elf.elf_base_mechanism_group.id</code>.
     */
    public ElfBaseMechanismGroupRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_mechanism_group.mechanism_id</code>.
     */
    public ElfBaseMechanismGroupRecord setMechanismId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism_group.mechanism_id</code>.
     */
    public Long getMechanismId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_mechanism_group.user_id</code>.
     */
    public ElfBaseMechanismGroupRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism_group.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.MECHANISM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMechanismId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMechanismId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismGroupRecord value2(Long value) {
        setMechanismId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismGroupRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismGroupRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseMechanismGroupRecord
     */
    public ElfBaseMechanismGroupRecord() {
        super(ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP);
    }

    /**
     * Create a detached, initialised ElfBaseMechanismGroupRecord
     */
    public ElfBaseMechanismGroupRecord(Long id, Long mechanismId, Long userId) {
        super(ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP);

        set(0, id);
        set(1, mechanismId);
        set(2, userId);
    }
}
