/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseMechanism;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 所属机构的汇总
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseMechanismRecord extends UpdatableRecordImpl<ElfBaseMechanismRecord> implements Record5<Long, Long, String, Long, Timestamp> {

    private static final long serialVersionUID = 526590436;

    /**
     * Setter for <code>elf.elf_base_mechanism.id</code>.
     */
    public ElfBaseMechanismRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_base_mechanism.mechanism_code</code>. 所属代号，显示给客户查看的
     */
    public ElfBaseMechanismRecord setMechanismCode(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism.mechanism_code</code>. 所属代号，显示给客户查看的
     */
    public Long getMechanismCode() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>elf.elf_base_mechanism.mechanism_name</code>. 机构名称
     */
    public ElfBaseMechanismRecord setMechanismName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism.mechanism_name</code>. 机构名称
     */
    public String getMechanismName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>elf.elf_base_mechanism.invalid</code>. 仓库是否失效 0 表示不失效，1表示失效
     */
    public ElfBaseMechanismRecord setInvalid(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism.invalid</code>. 仓库是否失效 0 表示不失效，1表示失效
     */
    public Long getInvalid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>elf.elf_base_mechanism.effective_date</code>. 失效日期，指这个机构在多久会失效，默认三年
     */
    public ElfBaseMechanismRecord setEffectiveDate(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_base_mechanism.effective_date</code>. 失效日期，指这个机构在多久会失效，默认三年
     */
    public Timestamp getEffectiveDate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Long, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Long, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfBaseMechanism.ELF_BASE_MECHANISM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ElfBaseMechanism.ELF_BASE_MECHANISM.MECHANISM_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ElfBaseMechanism.ELF_BASE_MECHANISM.MECHANISM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ElfBaseMechanism.ELF_BASE_MECHANISM.INVALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ElfBaseMechanism.ELF_BASE_MECHANISM.EFFECTIVE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMechanismCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMechanismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getInvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getEffectiveDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMechanismCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMechanismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getInvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getEffectiveDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismRecord value2(Long value) {
        setMechanismCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismRecord value3(String value) {
        setMechanismName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismRecord value4(Long value) {
        setInvalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismRecord value5(Timestamp value) {
        setEffectiveDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanismRecord values(Long value1, Long value2, String value3, Long value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfBaseMechanismRecord
     */
    public ElfBaseMechanismRecord() {
        super(ElfBaseMechanism.ELF_BASE_MECHANISM);
    }

    /**
     * Create a detached, initialised ElfBaseMechanismRecord
     */
    public ElfBaseMechanismRecord(Long id, Long mechanismCode, String mechanismName, Long invalid, Timestamp effectiveDate) {
        super(ElfBaseMechanism.ELF_BASE_MECHANISM);

        set(0, id);
        set(1, mechanismCode);
        set(2, mechanismName);
        set(3, invalid);
        set(4, effectiveDate);
    }
}
