/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import javax.annotation.Generated;

import org.elf.db.tables.ElfMenuDataMapping;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 菜单权限映射表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfMenuDataMappingRecord extends UpdatableRecordImpl<ElfMenuDataMappingRecord> implements Record4<Long, Long, Integer, Long> {

    private static final long serialVersionUID = -285718008;

    /**
     * Setter for <code>elf.elf_menu_data_mapping.id</code>. 唯一ID
     */
    public ElfMenuDataMappingRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data_mapping.id</code>. 唯一ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_menu_data_mapping.menu_id</code>.
     */
    public ElfMenuDataMappingRecord setMenuId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data_mapping.menu_id</code>.
     */
    public Long getMenuId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>elf.elf_menu_data_mapping.invalid</code>. 是否失效 0表示有效 1表示失效
     */
    public ElfMenuDataMappingRecord setInvalid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data_mapping.invalid</code>. 是否失效 0表示有效 1表示失效
     */
    public Integer getInvalid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>elf.elf_menu_data_mapping.role_id</code>. 所属的角色ID
     */
    public ElfMenuDataMappingRecord setRoleId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data_mapping.role_id</code>. 所属的角色ID
     */
    public Long getRoleId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Integer, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Integer, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfMenuDataMapping.ELF_MENU_DATA_MAPPING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ElfMenuDataMapping.ELF_MENU_DATA_MAPPING.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ElfMenuDataMapping.ELF_MENU_DATA_MAPPING.INVALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ElfMenuDataMapping.ELF_MENU_DATA_MAPPING.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getInvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getInvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMappingRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMappingRecord value2(Long value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMappingRecord value3(Integer value) {
        setInvalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMappingRecord value4(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMappingRecord values(Long value1, Long value2, Integer value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfMenuDataMappingRecord
     */
    public ElfMenuDataMappingRecord() {
        super(ElfMenuDataMapping.ELF_MENU_DATA_MAPPING);
    }

    /**
     * Create a detached, initialised ElfMenuDataMappingRecord
     */
    public ElfMenuDataMappingRecord(Long id, Long menuId, Integer invalid, Long roleId) {
        super(ElfMenuDataMapping.ELF_MENU_DATA_MAPPING);

        set(0, id);
        set(1, menuId);
        set(2, invalid);
        set(3, roleId);
    }
}
