/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables.records;


import javax.annotation.Generated;

import org.elf.db.tables.ElfMenuData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 基础的菜单信息维护
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfMenuDataRecord extends UpdatableRecordImpl<ElfMenuDataRecord> implements Record7<Long, Long, String, String, String, String, Long> {

    private static final long serialVersionUID = 2030045099;

    /**
     * Setter for <code>elf.elf_menu_data.id</code>.
     */
    public ElfMenuDataRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>elf.elf_menu_data.fatherId</code>. 父节点ID
     */
    public ElfMenuDataRecord setFatherid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.fatherId</code>. 父节点ID
     */
    public Long getFatherid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>elf.elf_menu_data.name</code>. 菜单名称
     */
    public ElfMenuDataRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.name</code>. 菜单名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>elf.elf_menu_data.icon</code>. 菜单图标
     */
    public ElfMenuDataRecord setIcon(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.icon</code>. 菜单图标
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>elf.elf_menu_data.path</code>. 路径
     */
    public ElfMenuDataRecord setPath(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.path</code>. 路径
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>elf.elf_menu_data.component</code>. 所属组件
     */
    public ElfMenuDataRecord setComponent(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.component</code>. 所属组件
     */
    public String getComponent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>elf.elf_menu_data.equipment_id</code>. 菜单所属的设备类型
     */
    public ElfMenuDataRecord setEquipmentId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>elf.elf_menu_data.equipment_id</code>. 菜单所属的设备类型
     */
    public Long getEquipmentId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ElfMenuData.ELF_MENU_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ElfMenuData.ELF_MENU_DATA.FATHERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ElfMenuData.ELF_MENU_DATA.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ElfMenuData.ELF_MENU_DATA.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ElfMenuData.ELF_MENU_DATA.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ElfMenuData.ELF_MENU_DATA.COMPONENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ElfMenuData.ELF_MENU_DATA.EQUIPMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFatherid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getComponent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFatherid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComponent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value2(Long value) {
        setFatherid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value4(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value5(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value6(String value) {
        setComponent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord value7(Long value) {
        setEquipmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElfMenuDataRecord
     */
    public ElfMenuDataRecord() {
        super(ElfMenuData.ELF_MENU_DATA);
    }

    /**
     * Create a detached, initialised ElfMenuDataRecord
     */
    public ElfMenuDataRecord(Long id, Long fatherid, String name, String icon, String path, String component, Long equipmentId) {
        super(ElfMenuData.ELF_MENU_DATA);

        set(0, id);
        set(1, fatherid);
        set(2, name);
        set(3, icon);
        set(4, path);
        set(5, component);
        set(6, equipmentId);
    }
}
