/*
 * This file is generated by jOOQ.
 */
package org.elf.db;


import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseEquipment;
import org.elf.db.tables.ElfBaseEquipmentGroup;
import org.elf.db.tables.ElfBaseLanguage;
import org.elf.db.tables.ElfBaseMechanism;
import org.elf.db.tables.ElfBaseMechanismGroup;
import org.elf.db.tables.ElfBaseRole;
import org.elf.db.tables.ElfBaseSession;
import org.elf.db.tables.ElfBaseUser;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>elf</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ELF_BASE_EQUIPMENT_PRIMARY = Indexes0.ELF_BASE_EQUIPMENT_PRIMARY;
    public static final Index ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_M_IDX = Indexes0.ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_M_IDX;
    public static final Index ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_ROLE_IDX = Indexes0.ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_ROLE_IDX;
    public static final Index ELF_BASE_EQUIPMENT_GROUP_PRIMARY = Indexes0.ELF_BASE_EQUIPMENT_GROUP_PRIMARY;
    public static final Index ELF_BASE_LANGUAGE_PRIMARY = Indexes0.ELF_BASE_LANGUAGE_PRIMARY;
    public static final Index ELF_BASE_MECHANISM_PRIMARY = Indexes0.ELF_BASE_MECHANISM_PRIMARY;
    public static final Index ELF_BASE_MECHANISM_GROUP_MECHANISM_GROUP_TO_MECHANISM_IDX = Indexes0.ELF_BASE_MECHANISM_GROUP_MECHANISM_GROUP_TO_MECHANISM_IDX;
    public static final Index ELF_BASE_MECHANISM_GROUP_MECHANISM_GROUP_TO_USER_IDX = Indexes0.ELF_BASE_MECHANISM_GROUP_MECHANISM_GROUP_TO_USER_IDX;
    public static final Index ELF_BASE_MECHANISM_GROUP_PRIMARY = Indexes0.ELF_BASE_MECHANISM_GROUP_PRIMARY;
    public static final Index ELF_BASE_ROLE_PRIMARY = Indexes0.ELF_BASE_ROLE_PRIMARY;
    public static final Index ELF_BASE_ROLE_ROLE_TO_MECHANISM_IDX = Indexes0.ELF_BASE_ROLE_ROLE_TO_MECHANISM_IDX;
    public static final Index ELF_BASE_SESSION_PRIMARY = Indexes0.ELF_BASE_SESSION_PRIMARY;
    public static final Index ELF_BASE_SESSION_SESSION_TO_EQUIPMENT_IDX = Indexes0.ELF_BASE_SESSION_SESSION_TO_EQUIPMENT_IDX;
    public static final Index ELF_BASE_SESSION_SESSION_TO_USER_IDX = Indexes0.ELF_BASE_SESSION_SESSION_TO_USER_IDX;
    public static final Index ELF_BASE_USER_LOGIN_NAME_UNIQUE = Indexes0.ELF_BASE_USER_LOGIN_NAME_UNIQUE;
    public static final Index ELF_BASE_USER_PRIMARY = Indexes0.ELF_BASE_USER_PRIMARY;
    public static final Index ELF_BASE_USER_USER_TO_ROLE_IDX = Indexes0.ELF_BASE_USER_USER_TO_ROLE_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ELF_BASE_EQUIPMENT_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseEquipment.ELF_BASE_EQUIPMENT, new OrderField[] { ElfBaseEquipment.ELF_BASE_EQUIPMENT.ID }, true);
        public static Index ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_M_IDX = Internal.createIndex("equipment_group_to_m_idx", ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP, new OrderField[] { ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.EQUIPMENT_ID }, false);
        public static Index ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_ROLE_IDX = Internal.createIndex("equipment_group_to_role_idx", ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP, new OrderField[] { ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.ROLE_ID }, false);
        public static Index ELF_BASE_EQUIPMENT_GROUP_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP, new OrderField[] { ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.ID }, true);
        public static Index ELF_BASE_LANGUAGE_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseLanguage.ELF_BASE_LANGUAGE, new OrderField[] { ElfBaseLanguage.ELF_BASE_LANGUAGE.ID }, true);
        public static Index ELF_BASE_MECHANISM_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseMechanism.ELF_BASE_MECHANISM, new OrderField[] { ElfBaseMechanism.ELF_BASE_MECHANISM.ID }, true);
        public static Index ELF_BASE_MECHANISM_GROUP_MECHANISM_GROUP_TO_MECHANISM_IDX = Internal.createIndex("mechanism_group_to_mechanism_idx", ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP, new OrderField[] { ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.MECHANISM_ID }, false);
        public static Index ELF_BASE_MECHANISM_GROUP_MECHANISM_GROUP_TO_USER_IDX = Internal.createIndex("mechanism_group_to_user_idx", ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP, new OrderField[] { ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.USER_ID }, false);
        public static Index ELF_BASE_MECHANISM_GROUP_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP, new OrderField[] { ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.ID }, true);
        public static Index ELF_BASE_ROLE_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseRole.ELF_BASE_ROLE, new OrderField[] { ElfBaseRole.ELF_BASE_ROLE.ID }, true);
        public static Index ELF_BASE_ROLE_ROLE_TO_MECHANISM_IDX = Internal.createIndex("role_to_mechanism_idx", ElfBaseRole.ELF_BASE_ROLE, new OrderField[] { ElfBaseRole.ELF_BASE_ROLE.MECHANISM_ID }, false);
        public static Index ELF_BASE_SESSION_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseSession.ELF_BASE_SESSION, new OrderField[] { ElfBaseSession.ELF_BASE_SESSION.ID }, true);
        public static Index ELF_BASE_SESSION_SESSION_TO_EQUIPMENT_IDX = Internal.createIndex("session_to_equipment_idx", ElfBaseSession.ELF_BASE_SESSION, new OrderField[] { ElfBaseSession.ELF_BASE_SESSION.EQUIPMENT_ID }, false);
        public static Index ELF_BASE_SESSION_SESSION_TO_USER_IDX = Internal.createIndex("session_to_user_idx", ElfBaseSession.ELF_BASE_SESSION, new OrderField[] { ElfBaseSession.ELF_BASE_SESSION.USER_ID }, false);
        public static Index ELF_BASE_USER_LOGIN_NAME_UNIQUE = Internal.createIndex("login_name_UNIQUE", ElfBaseUser.ELF_BASE_USER, new OrderField[] { ElfBaseUser.ELF_BASE_USER.LOGIN_NAME }, true);
        public static Index ELF_BASE_USER_PRIMARY = Internal.createIndex("PRIMARY", ElfBaseUser.ELF_BASE_USER, new OrderField[] { ElfBaseUser.ELF_BASE_USER.ID }, true);
        public static Index ELF_BASE_USER_USER_TO_ROLE_IDX = Internal.createIndex("user_to_role_idx", ElfBaseUser.ELF_BASE_USER, new OrderField[] { ElfBaseUser.ELF_BASE_USER.ROLE_ID }, false);
    }
}
