/*
 * This file is generated by jOOQ.
 */
package org.elf.db;


import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseEquipment;
import org.elf.db.tables.ElfBaseEquipmentGroup;
import org.elf.db.tables.ElfBaseLanguage;
import org.elf.db.tables.ElfBaseMechanism;
import org.elf.db.tables.ElfBaseMechanismGroup;
import org.elf.db.tables.ElfBaseRole;
import org.elf.db.tables.ElfBaseSession;
import org.elf.db.tables.ElfBaseUser;
import org.elf.db.tables.ElfMenuData;
import org.elf.db.tables.ElfMenuDataMapping;
import org.elf.db.tables.records.ElfBaseEquipmentGroupRecord;
import org.elf.db.tables.records.ElfBaseEquipmentRecord;
import org.elf.db.tables.records.ElfBaseLanguageRecord;
import org.elf.db.tables.records.ElfBaseMechanismGroupRecord;
import org.elf.db.tables.records.ElfBaseMechanismRecord;
import org.elf.db.tables.records.ElfBaseRoleRecord;
import org.elf.db.tables.records.ElfBaseSessionRecord;
import org.elf.db.tables.records.ElfBaseUserRecord;
import org.elf.db.tables.records.ElfMenuDataMappingRecord;
import org.elf.db.tables.records.ElfMenuDataRecord;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>elf</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ElfBaseEquipmentRecord> KEY_ELF_BASE_EQUIPMENT_PRIMARY = UniqueKeys0.KEY_ELF_BASE_EQUIPMENT_PRIMARY;
    public static final UniqueKey<ElfBaseEquipmentGroupRecord> KEY_ELF_BASE_EQUIPMENT_GROUP_PRIMARY = UniqueKeys0.KEY_ELF_BASE_EQUIPMENT_GROUP_PRIMARY;
    public static final UniqueKey<ElfBaseLanguageRecord> KEY_ELF_BASE_LANGUAGE_PRIMARY = UniqueKeys0.KEY_ELF_BASE_LANGUAGE_PRIMARY;
    public static final UniqueKey<ElfBaseMechanismRecord> KEY_ELF_BASE_MECHANISM_PRIMARY = UniqueKeys0.KEY_ELF_BASE_MECHANISM_PRIMARY;
    public static final UniqueKey<ElfBaseMechanismGroupRecord> KEY_ELF_BASE_MECHANISM_GROUP_PRIMARY = UniqueKeys0.KEY_ELF_BASE_MECHANISM_GROUP_PRIMARY;
    public static final UniqueKey<ElfBaseRoleRecord> KEY_ELF_BASE_ROLE_PRIMARY = UniqueKeys0.KEY_ELF_BASE_ROLE_PRIMARY;
    public static final UniqueKey<ElfBaseSessionRecord> KEY_ELF_BASE_SESSION_PRIMARY = UniqueKeys0.KEY_ELF_BASE_SESSION_PRIMARY;
    public static final UniqueKey<ElfBaseUserRecord> KEY_ELF_BASE_USER_PRIMARY = UniqueKeys0.KEY_ELF_BASE_USER_PRIMARY;
    public static final UniqueKey<ElfBaseUserRecord> KEY_ELF_BASE_USER_LOGIN_NAME_UNIQUE = UniqueKeys0.KEY_ELF_BASE_USER_LOGIN_NAME_UNIQUE;
    public static final UniqueKey<ElfMenuDataRecord> KEY_ELF_MENU_DATA_PRIMARY = UniqueKeys0.KEY_ELF_MENU_DATA_PRIMARY;
    public static final UniqueKey<ElfMenuDataMappingRecord> KEY_ELF_MENU_DATA_MAPPING_PRIMARY = UniqueKeys0.KEY_ELF_MENU_DATA_MAPPING_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ElfBaseEquipmentGroupRecord, ElfBaseRoleRecord> EQUIPMENT_GROUP_TO_ROLE = ForeignKeys0.EQUIPMENT_GROUP_TO_ROLE;
    public static final ForeignKey<ElfBaseEquipmentGroupRecord, ElfBaseEquipmentRecord> EQUIPMENT_GROUP_TO_M = ForeignKeys0.EQUIPMENT_GROUP_TO_M;
    public static final ForeignKey<ElfBaseMechanismGroupRecord, ElfBaseMechanismRecord> MECHANISM_GROUP_TO_MECHANISM = ForeignKeys0.MECHANISM_GROUP_TO_MECHANISM;
    public static final ForeignKey<ElfBaseMechanismGroupRecord, ElfBaseUserRecord> MECHANISM_GROUP_TO_USER = ForeignKeys0.MECHANISM_GROUP_TO_USER;
    public static final ForeignKey<ElfBaseRoleRecord, ElfBaseMechanismRecord> ROLE_TO_MECHANISM = ForeignKeys0.ROLE_TO_MECHANISM;
    public static final ForeignKey<ElfBaseSessionRecord, ElfBaseUserRecord> SESSION_TO_USER = ForeignKeys0.SESSION_TO_USER;
    public static final ForeignKey<ElfBaseSessionRecord, ElfBaseEquipmentRecord> SESSION_TO_EQUIPMENT = ForeignKeys0.SESSION_TO_EQUIPMENT;
    public static final ForeignKey<ElfBaseUserRecord, ElfBaseRoleRecord> USER_TO_ROLE = ForeignKeys0.USER_TO_ROLE;
    public static final ForeignKey<ElfMenuDataMappingRecord, ElfMenuDataRecord> FKEY_MENU_DATA_MAPPING_TO_MENU_DATA = ForeignKeys0.FKEY_MENU_DATA_MAPPING_TO_MENU_DATA;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ElfBaseEquipmentRecord> KEY_ELF_BASE_EQUIPMENT_PRIMARY = Internal.createUniqueKey(ElfBaseEquipment.ELF_BASE_EQUIPMENT, "KEY_elf_base_equipment_PRIMARY", ElfBaseEquipment.ELF_BASE_EQUIPMENT.ID);
        public static final UniqueKey<ElfBaseEquipmentGroupRecord> KEY_ELF_BASE_EQUIPMENT_GROUP_PRIMARY = Internal.createUniqueKey(ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP, "KEY_elf_base_equipment_group_PRIMARY", ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.ID);
        public static final UniqueKey<ElfBaseLanguageRecord> KEY_ELF_BASE_LANGUAGE_PRIMARY = Internal.createUniqueKey(ElfBaseLanguage.ELF_BASE_LANGUAGE, "KEY_elf_base_language_PRIMARY", ElfBaseLanguage.ELF_BASE_LANGUAGE.ID);
        public static final UniqueKey<ElfBaseMechanismRecord> KEY_ELF_BASE_MECHANISM_PRIMARY = Internal.createUniqueKey(ElfBaseMechanism.ELF_BASE_MECHANISM, "KEY_elf_base_mechanism_PRIMARY", ElfBaseMechanism.ELF_BASE_MECHANISM.ID);
        public static final UniqueKey<ElfBaseMechanismGroupRecord> KEY_ELF_BASE_MECHANISM_GROUP_PRIMARY = Internal.createUniqueKey(ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP, "KEY_elf_base_mechanism_group_PRIMARY", ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.ID);
        public static final UniqueKey<ElfBaseRoleRecord> KEY_ELF_BASE_ROLE_PRIMARY = Internal.createUniqueKey(ElfBaseRole.ELF_BASE_ROLE, "KEY_elf_base_role_PRIMARY", ElfBaseRole.ELF_BASE_ROLE.ID);
        public static final UniqueKey<ElfBaseSessionRecord> KEY_ELF_BASE_SESSION_PRIMARY = Internal.createUniqueKey(ElfBaseSession.ELF_BASE_SESSION, "KEY_elf_base_session_PRIMARY", ElfBaseSession.ELF_BASE_SESSION.ID);
        public static final UniqueKey<ElfBaseUserRecord> KEY_ELF_BASE_USER_PRIMARY = Internal.createUniqueKey(ElfBaseUser.ELF_BASE_USER, "KEY_elf_base_user_PRIMARY", ElfBaseUser.ELF_BASE_USER.ID);
        public static final UniqueKey<ElfBaseUserRecord> KEY_ELF_BASE_USER_LOGIN_NAME_UNIQUE = Internal.createUniqueKey(ElfBaseUser.ELF_BASE_USER, "KEY_elf_base_user_login_name_UNIQUE", ElfBaseUser.ELF_BASE_USER.LOGIN_NAME);
        public static final UniqueKey<ElfMenuDataRecord> KEY_ELF_MENU_DATA_PRIMARY = Internal.createUniqueKey(ElfMenuData.ELF_MENU_DATA, "KEY_elf_menu_data_PRIMARY", ElfMenuData.ELF_MENU_DATA.ID);
        public static final UniqueKey<ElfMenuDataMappingRecord> KEY_ELF_MENU_DATA_MAPPING_PRIMARY = Internal.createUniqueKey(ElfMenuDataMapping.ELF_MENU_DATA_MAPPING, "KEY_elf_menu_data_mapping_PRIMARY", ElfMenuDataMapping.ELF_MENU_DATA_MAPPING.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ElfBaseEquipmentGroupRecord, ElfBaseRoleRecord> EQUIPMENT_GROUP_TO_ROLE = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_ROLE_PRIMARY, ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP, "equipment_group_to_role", ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.ROLE_ID);
        public static final ForeignKey<ElfBaseEquipmentGroupRecord, ElfBaseEquipmentRecord> EQUIPMENT_GROUP_TO_M = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_EQUIPMENT_PRIMARY, ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP, "equipment_group_to_m", ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP.EQUIPMENT_ID);
        public static final ForeignKey<ElfBaseMechanismGroupRecord, ElfBaseMechanismRecord> MECHANISM_GROUP_TO_MECHANISM = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_MECHANISM_PRIMARY, ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP, "mechanism_group_to_mechanism", ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.MECHANISM_ID);
        public static final ForeignKey<ElfBaseMechanismGroupRecord, ElfBaseUserRecord> MECHANISM_GROUP_TO_USER = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_USER_PRIMARY, ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP, "mechanism_group_to_user", ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP.USER_ID);
        public static final ForeignKey<ElfBaseRoleRecord, ElfBaseMechanismRecord> ROLE_TO_MECHANISM = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_MECHANISM_PRIMARY, ElfBaseRole.ELF_BASE_ROLE, "role_to_mechanism", ElfBaseRole.ELF_BASE_ROLE.MECHANISM_ID);
        public static final ForeignKey<ElfBaseSessionRecord, ElfBaseUserRecord> SESSION_TO_USER = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_USER_PRIMARY, ElfBaseSession.ELF_BASE_SESSION, "session_to_user", ElfBaseSession.ELF_BASE_SESSION.USER_ID);
        public static final ForeignKey<ElfBaseSessionRecord, ElfBaseEquipmentRecord> SESSION_TO_EQUIPMENT = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_EQUIPMENT_PRIMARY, ElfBaseSession.ELF_BASE_SESSION, "session_to_equipment", ElfBaseSession.ELF_BASE_SESSION.EQUIPMENT_ID);
        public static final ForeignKey<ElfBaseUserRecord, ElfBaseRoleRecord> USER_TO_ROLE = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_BASE_ROLE_PRIMARY, ElfBaseUser.ELF_BASE_USER, "user_to_role", ElfBaseUser.ELF_BASE_USER.ROLE_ID);
        public static final ForeignKey<ElfMenuDataMappingRecord, ElfMenuDataRecord> FKEY_MENU_DATA_MAPPING_TO_MENU_DATA = Internal.createForeignKey(org.elf.db.Keys.KEY_ELF_MENU_DATA_PRIMARY, ElfMenuDataMapping.ELF_MENU_DATA_MAPPING, "FKEY_MENU_DATA_MAPPING_TO_MENU_DATA", ElfMenuDataMapping.ELF_MENU_DATA_MAPPING.MENU_ID);
    }
}
