/*
 * This file is generated by jOOQ.
 */
package org.elf.db;


import javax.annotation.Generated;

import org.elf.db.tables.ElfBaseEquipment;
import org.elf.db.tables.ElfBaseEquipmentGroup;
import org.elf.db.tables.ElfBaseLanguage;
import org.elf.db.tables.ElfBaseMechanism;
import org.elf.db.tables.ElfBaseMechanismGroup;
import org.elf.db.tables.ElfBaseRole;
import org.elf.db.tables.ElfBaseSession;
import org.elf.db.tables.ElfBaseUser;


/**
 * Convenience access to all tables in elf
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 设备信息维护表
     */
    public static final ElfBaseEquipment ELF_BASE_EQUIPMENT = org.elf.db.tables.ElfBaseEquipment.ELF_BASE_EQUIPMENT;

    /**
     * 设备信息分组表
     */
    public static final ElfBaseEquipmentGroup ELF_BASE_EQUIPMENT_GROUP = org.elf.db.tables.ElfBaseEquipmentGroup.ELF_BASE_EQUIPMENT_GROUP;

    /**
     * 用来做国际化翻译后台的提示信息
     */
    public static final ElfBaseLanguage ELF_BASE_LANGUAGE = org.elf.db.tables.ElfBaseLanguage.ELF_BASE_LANGUAGE;

    /**
     * 所属机构的汇总
     */
    public static final ElfBaseMechanism ELF_BASE_MECHANISM = org.elf.db.tables.ElfBaseMechanism.ELF_BASE_MECHANISM;

    /**
     * 所属机构，和用户对应的详细信息
     */
    public static final ElfBaseMechanismGroup ELF_BASE_MECHANISM_GROUP = org.elf.db.tables.ElfBaseMechanismGroup.ELF_BASE_MECHANISM_GROUP;

    /**
     * 角色信息管理
     */
    public static final ElfBaseRole ELF_BASE_ROLE = org.elf.db.tables.ElfBaseRole.ELF_BASE_ROLE;

    /**
     * 维护用户当前登入的session
     */
    public static final ElfBaseSession ELF_BASE_SESSION = org.elf.db.tables.ElfBaseSession.ELF_BASE_SESSION;

    /**
     * 用来维护用户信息
     */
    public static final ElfBaseUser ELF_BASE_USER = org.elf.db.tables.ElfBaseUser.ELF_BASE_USER;
}
