/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elf.db.Elf;
import org.elf.db.Indexes;
import org.elf.db.Keys;
import org.elf.db.tables.records.ElfBaseEquipmentGroupRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 设备信息分组表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseEquipmentGroup extends TableImpl<ElfBaseEquipmentGroupRecord> {

    private static final long serialVersionUID = -1952308139;

    /**
     * The reference instance of <code>elf.elf_base_equipment_group</code>
     */
    public static final ElfBaseEquipmentGroup ELF_BASE_EQUIPMENT_GROUP = new ElfBaseEquipmentGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ElfBaseEquipmentGroupRecord> getRecordType() {
        return ElfBaseEquipmentGroupRecord.class;
    }

    /**
     * The column <code>elf.elf_base_equipment_group.id</code>.
     */
    public final TableField<ElfBaseEquipmentGroupRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>elf.elf_base_equipment_group.role_id</code>. 角色ID
     */
    public final TableField<ElfBaseEquipmentGroupRecord, Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "角色ID");

    /**
     * The column <code>elf.elf_base_equipment_group.equipment_id</code>. 设备ID
     */
    public final TableField<ElfBaseEquipmentGroupRecord, Long> EQUIPMENT_ID = createField("equipment_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "设备ID");

    /**
     * The column <code>elf.elf_base_equipment_group.invalid</code>. 是否失效 0表示否 1表示失效
     */
    public final TableField<ElfBaseEquipmentGroupRecord, Integer> INVALID = createField("invalid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "是否失效 0表示否 1表示失效");

    /**
     * Create a <code>elf.elf_base_equipment_group</code> table reference
     */
    public ElfBaseEquipmentGroup() {
        this(DSL.name("elf_base_equipment_group"), null);
    }

    /**
     * Create an aliased <code>elf.elf_base_equipment_group</code> table reference
     */
    public ElfBaseEquipmentGroup(String alias) {
        this(DSL.name(alias), ELF_BASE_EQUIPMENT_GROUP);
    }

    /**
     * Create an aliased <code>elf.elf_base_equipment_group</code> table reference
     */
    public ElfBaseEquipmentGroup(Name alias) {
        this(alias, ELF_BASE_EQUIPMENT_GROUP);
    }

    private ElfBaseEquipmentGroup(Name alias, Table<ElfBaseEquipmentGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private ElfBaseEquipmentGroup(Name alias, Table<ElfBaseEquipmentGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("设备信息分组表"));
    }

    public <O extends Record> ElfBaseEquipmentGroup(Table<O> child, ForeignKey<O, ElfBaseEquipmentGroupRecord> key) {
        super(child, key, ELF_BASE_EQUIPMENT_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Elf.ELF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_M_IDX, Indexes.ELF_BASE_EQUIPMENT_GROUP_EQUIPMENT_GROUP_TO_ROLE_IDX, Indexes.ELF_BASE_EQUIPMENT_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ElfBaseEquipmentGroupRecord> getPrimaryKey() {
        return Keys.KEY_ELF_BASE_EQUIPMENT_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ElfBaseEquipmentGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<ElfBaseEquipmentGroupRecord>>asList(Keys.KEY_ELF_BASE_EQUIPMENT_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ElfBaseEquipmentGroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ElfBaseEquipmentGroupRecord, ?>>asList(Keys.EQUIPMENT_GROUP_TO_ROLE, Keys.EQUIPMENT_GROUP_TO_M);
    }

    public ElfBaseRole elfBaseRole() {
        return new ElfBaseRole(this, Keys.EQUIPMENT_GROUP_TO_ROLE);
    }

    public ElfBaseEquipment elfBaseEquipment() {
        return new ElfBaseEquipment(this, Keys.EQUIPMENT_GROUP_TO_M);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroup as(String alias) {
        return new ElfBaseEquipmentGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseEquipmentGroup as(Name alias) {
        return new ElfBaseEquipmentGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfBaseEquipmentGroup rename(String name) {
        return new ElfBaseEquipmentGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfBaseEquipmentGroup rename(Name name) {
        return new ElfBaseEquipmentGroup(name, null);
    }
}
