/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elf.db.Elf;
import org.elf.db.Indexes;
import org.elf.db.Keys;
import org.elf.db.tables.records.ElfBaseMechanismRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 所属机构的汇总
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfBaseMechanism extends TableImpl<ElfBaseMechanismRecord> {

    private static final long serialVersionUID = 236927757;

    /**
     * The reference instance of <code>elf.elf_base_mechanism</code>
     */
    public static final ElfBaseMechanism ELF_BASE_MECHANISM = new ElfBaseMechanism();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ElfBaseMechanismRecord> getRecordType() {
        return ElfBaseMechanismRecord.class;
    }

    /**
     * The column <code>elf.elf_base_mechanism.id</code>.
     */
    public final TableField<ElfBaseMechanismRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>elf.elf_base_mechanism.mechanism_code</code>. 所属代号，显示给客户查看的
     */
    public final TableField<ElfBaseMechanismRecord, Long> MECHANISM_CODE = createField("mechanism_code", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "所属代号，显示给客户查看的");

    /**
     * The column <code>elf.elf_base_mechanism.mechanism_name</code>. 机构名称
     */
    public final TableField<ElfBaseMechanismRecord, String> MECHANISM_NAME = createField("mechanism_name", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "机构名称");

    /**
     * The column <code>elf.elf_base_mechanism.invalid</code>. 仓库是否失效 0 表示不失效，1表示失效
     */
    public final TableField<ElfBaseMechanismRecord, Long> INVALID = createField("invalid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "仓库是否失效 0 表示不失效，1表示失效");

    /**
     * The column <code>elf.elf_base_mechanism.effective_date</code>. 失效日期，指这个机构在多久会失效，默认三年
     */
    public final TableField<ElfBaseMechanismRecord, Timestamp> EFFECTIVE_DATE = createField("effective_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "失效日期，指这个机构在多久会失效，默认三年");

    /**
     * Create a <code>elf.elf_base_mechanism</code> table reference
     */
    public ElfBaseMechanism() {
        this(DSL.name("elf_base_mechanism"), null);
    }

    /**
     * Create an aliased <code>elf.elf_base_mechanism</code> table reference
     */
    public ElfBaseMechanism(String alias) {
        this(DSL.name(alias), ELF_BASE_MECHANISM);
    }

    /**
     * Create an aliased <code>elf.elf_base_mechanism</code> table reference
     */
    public ElfBaseMechanism(Name alias) {
        this(alias, ELF_BASE_MECHANISM);
    }

    private ElfBaseMechanism(Name alias, Table<ElfBaseMechanismRecord> aliased) {
        this(alias, aliased, null);
    }

    private ElfBaseMechanism(Name alias, Table<ElfBaseMechanismRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("所属机构的汇总"));
    }

    public <O extends Record> ElfBaseMechanism(Table<O> child, ForeignKey<O, ElfBaseMechanismRecord> key) {
        super(child, key, ELF_BASE_MECHANISM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Elf.ELF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ELF_BASE_MECHANISM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ElfBaseMechanismRecord> getPrimaryKey() {
        return Keys.KEY_ELF_BASE_MECHANISM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ElfBaseMechanismRecord>> getKeys() {
        return Arrays.<UniqueKey<ElfBaseMechanismRecord>>asList(Keys.KEY_ELF_BASE_MECHANISM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanism as(String alias) {
        return new ElfBaseMechanism(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfBaseMechanism as(Name alias) {
        return new ElfBaseMechanism(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfBaseMechanism rename(String name) {
        return new ElfBaseMechanism(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfBaseMechanism rename(Name name) {
        return new ElfBaseMechanism(name, null);
    }
}
