/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elf.db.Elf;
import org.elf.db.Indexes;
import org.elf.db.Keys;
import org.elf.db.tables.records.ElfMenuDataMappingRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 菜单权限映射表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfMenuDataMapping extends TableImpl<ElfMenuDataMappingRecord> {

    private static final long serialVersionUID = 525109750;

    /**
     * The reference instance of <code>elf.elf_menu_data_mapping</code>
     */
    public static final ElfMenuDataMapping ELF_MENU_DATA_MAPPING = new ElfMenuDataMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ElfMenuDataMappingRecord> getRecordType() {
        return ElfMenuDataMappingRecord.class;
    }

    /**
     * The column <code>elf.elf_menu_data_mapping.id</code>. 唯一ID
     */
    public final TableField<ElfMenuDataMappingRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "唯一ID");

    /**
     * The column <code>elf.elf_menu_data_mapping.menu_id</code>.
     */
    public final TableField<ElfMenuDataMappingRecord, Long> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>elf.elf_menu_data_mapping.invalid</code>. 是否失效 0表示有效 1表示失效
     */
    public final TableField<ElfMenuDataMappingRecord, Integer> INVALID = createField("invalid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否失效 0表示有效 1表示失效");

    /**
     * The column <code>elf.elf_menu_data_mapping.role_id</code>. 所属的角色ID
     */
    public final TableField<ElfMenuDataMappingRecord, Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "所属的角色ID");

    /**
     * Create a <code>elf.elf_menu_data_mapping</code> table reference
     */
    public ElfMenuDataMapping() {
        this(DSL.name("elf_menu_data_mapping"), null);
    }

    /**
     * Create an aliased <code>elf.elf_menu_data_mapping</code> table reference
     */
    public ElfMenuDataMapping(String alias) {
        this(DSL.name(alias), ELF_MENU_DATA_MAPPING);
    }

    /**
     * Create an aliased <code>elf.elf_menu_data_mapping</code> table reference
     */
    public ElfMenuDataMapping(Name alias) {
        this(alias, ELF_MENU_DATA_MAPPING);
    }

    private ElfMenuDataMapping(Name alias, Table<ElfMenuDataMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private ElfMenuDataMapping(Name alias, Table<ElfMenuDataMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("菜单权限映射表"));
    }

    public <O extends Record> ElfMenuDataMapping(Table<O> child, ForeignKey<O, ElfMenuDataMappingRecord> key) {
        super(child, key, ELF_MENU_DATA_MAPPING);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Elf.ELF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ELF_MENU_DATA_MAPPING_FKEY_MENU_DATA_MAPPING_TO_MENU_DATA_IDX, Indexes.ELF_MENU_DATA_MAPPING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ElfMenuDataMappingRecord> getPrimaryKey() {
        return Keys.KEY_ELF_MENU_DATA_MAPPING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ElfMenuDataMappingRecord>> getKeys() {
        return Arrays.<UniqueKey<ElfMenuDataMappingRecord>>asList(Keys.KEY_ELF_MENU_DATA_MAPPING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ElfMenuDataMappingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ElfMenuDataMappingRecord, ?>>asList(Keys.FKEY_MENU_DATA_MAPPING_TO_MENU_DATA);
    }

    public ElfMenuData elfMenuData() {
        return new ElfMenuData(this, Keys.FKEY_MENU_DATA_MAPPING_TO_MENU_DATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMapping as(String alias) {
        return new ElfMenuDataMapping(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuDataMapping as(Name alias) {
        return new ElfMenuDataMapping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfMenuDataMapping rename(String name) {
        return new ElfMenuDataMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfMenuDataMapping rename(Name name) {
        return new ElfMenuDataMapping(name, null);
    }
}
