/*
 * This file is generated by jOOQ.
 */
package org.elf.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elf.db.Elf;
import org.elf.db.Indexes;
import org.elf.db.Keys;
import org.elf.db.tables.records.ElfMenuDataRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 基础的菜单信息维护
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElfMenuData extends TableImpl<ElfMenuDataRecord> {

    private static final long serialVersionUID = 1695636427;

    /**
     * The reference instance of <code>elf.elf_menu_data</code>
     */
    public static final ElfMenuData ELF_MENU_DATA = new ElfMenuData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ElfMenuDataRecord> getRecordType() {
        return ElfMenuDataRecord.class;
    }

    /**
     * The column <code>elf.elf_menu_data.id</code>.
     */
    public final TableField<ElfMenuDataRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>elf.elf_menu_data.fatherId</code>. 父节点ID
     */
    public final TableField<ElfMenuDataRecord, Long> FATHERID = createField("fatherId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "父节点ID");

    /**
     * The column <code>elf.elf_menu_data.name</code>. 菜单名称
     */
    public final TableField<ElfMenuDataRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "菜单名称");

    /**
     * The column <code>elf.elf_menu_data.icon</code>. 菜单图标
     */
    public final TableField<ElfMenuDataRecord, String> ICON = createField("icon", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "菜单图标");

    /**
     * The column <code>elf.elf_menu_data.path</code>. 路径
     */
    public final TableField<ElfMenuDataRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "路径");

    /**
     * The column <code>elf.elf_menu_data.component</code>. 所属组件
     */
    public final TableField<ElfMenuDataRecord, String> COMPONENT = createField("component", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "所属组件");

    /**
     * The column <code>elf.elf_menu_data.equipment_id</code>. 菜单所属的设备类型
     */
    public final TableField<ElfMenuDataRecord, Long> EQUIPMENT_ID = createField("equipment_id", org.jooq.impl.SQLDataType.BIGINT, this, "菜单所属的设备类型");

    /**
     * Create a <code>elf.elf_menu_data</code> table reference
     */
    public ElfMenuData() {
        this(DSL.name("elf_menu_data"), null);
    }

    /**
     * Create an aliased <code>elf.elf_menu_data</code> table reference
     */
    public ElfMenuData(String alias) {
        this(DSL.name(alias), ELF_MENU_DATA);
    }

    /**
     * Create an aliased <code>elf.elf_menu_data</code> table reference
     */
    public ElfMenuData(Name alias) {
        this(alias, ELF_MENU_DATA);
    }

    private ElfMenuData(Name alias, Table<ElfMenuDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private ElfMenuData(Name alias, Table<ElfMenuDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("基础的菜单信息维护"));
    }

    public <O extends Record> ElfMenuData(Table<O> child, ForeignKey<O, ElfMenuDataRecord> key) {
        super(child, key, ELF_MENU_DATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Elf.ELF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ELF_MENU_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ElfMenuDataRecord> getPrimaryKey() {
        return Keys.KEY_ELF_MENU_DATA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ElfMenuDataRecord>> getKeys() {
        return Arrays.<UniqueKey<ElfMenuDataRecord>>asList(Keys.KEY_ELF_MENU_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuData as(String alias) {
        return new ElfMenuData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ElfMenuData as(Name alias) {
        return new ElfMenuData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfMenuData rename(String name) {
        return new ElfMenuData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElfMenuData rename(Name name) {
        return new ElfMenuData(name, null);
    }
}
